### ISSUE TITLE
Click to view post broken

### ISSUE THREAD

**Issue by Xoin** [Xoin/Awfully-White#2]
Click to view post doesn't show up till refreshing.

```css
body.page-forum .threadviewsection .postblock .postmain .postexpand.expandable-overflown:after {
          content: 'Click to view full post..';
          display: flex;
          position: absolute;
          bottom: 0px;
          right: 0px;
          left: 0px;
          margin: 0 1rem;
          text-align: center;
          background: #4fa052;
          color: rgba(255, 255, 255, 0.9);
          font-size: 0.7rem;
          align-items: flex-end;
          padding: 1rem; }
```
