### ISSUE TITLE
Bottom navbar pushes shit off screen on mobile

### ISSUE THREAD

**Issue by Xoin** [Xoin/Awfully-White#4]
```css
@media screen and (min-width: 800px)
main?q=8d53ce9a42ff570:4670
.navbar > .container .navbar-brand, .container > .navbar .navbar-brand {
    margin-left: -1rem;
}
```

```css
@media screen and (min-width: 800px)
main?q=8d53ce9a42ff570:4675
.navbar > .container .navbar-menu, .container > .navbar .navbar-menu {
    margin-right: -1rem;
}
```
